# Generated by Django 4.0.3 on 2022-07-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsandrecognistionteachersstudents',
            name='awardee_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
