# Generated by Django 4.0.3 on 2022-04-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.RemoveField(
            model_name='collabrativeactivity',
            name='sl_no',
        ),
        migrations.AddField(
            model_name='collabrativeactivity',
            name='student_or_faculty',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='Student', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bos',
            name='skils_development',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collabrativeactivity',
            name='participant_USN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
