# Generated by Django 4.0.3 on 2022-03-29 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=255)),
                ('journal_title', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('entered_date', models.DateField(auto_now_add=True)),
                ('impact_factor', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_faculty', to='api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=255)),
                ('conference_title', models.CharField(max_length=255)),
                ('event_date', models.DateField(auto_now_add=True)),
                ('organised_by', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_faculty', to='api.faculty')),
            ],
        ),
    ]
