# Generated by Django 4.0.3 on 2022-04-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_awards_remove_collabrativeactivity_sl_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='co_principal_investigator',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conferenceattendedbyteachers',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conferenceconductedincollege',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listmajorminorresearchprojects',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
