# Generated by Django 4.0.3 on 2022-04-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_grant_co_principal_investigator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='number_of_students_enrolled',
        ),
    ]
