# Generated by Django 4.0.3 on 2022-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_course_number_of_students_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bos',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
