# Generated by Django 4.0.3 on 2022-04-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bos_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_with_details', models.TextField()),
                ('usn', models.CharField(max_length=255)),
                ('program', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], max_length=255)),
                ('type_of_activity', models.CharField(choices=[('Exta-Curricular', 'Extra-Curricular'), ('Co-Curricular', 'Co-Curricular')], max_length=255)),
                ('award', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='TotalAmountSpentOnFacilities',
            new_name='FundingStudentProjects',
        ),
        migrations.RenameField(
            model_name='consultants',
            old_name='department',
            new_name='sponsoring_agency_details',
        ),
        migrations.RemoveField(
            model_name='awardsandrecognistionteachersstudents',
            name='awarding_government_name',
        ),
        migrations.RemoveField(
            model_name='bos',
            name='skils_development',
        ),
        migrations.RemoveField(
            model_name='collabrativeactivity',
            name='collabrating_agency_contact',
        ),
        migrations.RemoveField(
            model_name='conferenceconductedincollege',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='consultants',
            name='sponsoring_agency',
        ),
        migrations.AddField(
            model_name='awardsandrecognistionteachersstudents',
            name='awarding_organization_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awardsandrecognistionteachersstudents',
            name='type',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bos',
            name='activity',
            field=models.CharField(choices=[('Entreprenuership', 'Entreprenuership'), ('Employability', 'Employability'), ('Skill Development', 'Skill Development')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collabrativeactivity',
            name='collabrating_agency_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collabrativeactivity',
            name='nature_of_activity',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferenceconductedincollege',
            name='resource_person_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conferenceattendedbyteachers',
            name='presented_papers_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conferenceattendedbyteachers',
            name='type',
            field=models.CharField(choices=[('International', 'International'), ('National', 'National')], max_length=255),
        ),
    ]
