# Generated by Django 4.0.3 on 2022-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCoursesIntroduced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('duration_of_course', models.CharField(max_length=255)),
                ('activity', models.CharField(choices=[('Entreprenuership', 'Entreprenuership'), ('Employability', 'Employability'), ('Skill Development', 'Skill Development')], max_length=255)),
                ('year_of_introduction', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterField(
            model_name='consultants',
            name='sponsoring_agency_details',
            field=models.TextField(),
        ),
    ]
