# Generated by Django 4.0.3 on 2022-04-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_newcoursesintroduced_delete_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyprofile',
            old_name='type',
            new_name='appointment_type',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='if_visiting_faculty',
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='industry_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='visiting_faculty',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='visiting_faculty_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='industry_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
